In [47]:
import h5py
import numpy as np
from scipy.io import loadmat

In [48]:
file = "D:\\documents\\usp\\masters\\research\\dns_code\\GATT_DNS\\py\\baseflow_gap_Re950_M01_h10_LR18\\mesh.npz"
mesh = np.load(file, allow_pickle= True)

In [49]:
mesh['Y']

array([-1.00000000e-01, -9.00000000e-02, -8.00000000e-02, -7.00000000e-02,
       -6.00000000e-02, -5.00000000e-02, -4.00000000e-02, -3.00000000e-02,
       -2.00000000e-02, -1.00000000e-02,  0.00000000e+00,  1.00000000e-02,
        2.00000000e-02,  3.00000000e-02,  4.00000000e-02,  5.00000000e-02,
        6.00000000e-02,  7.00000000e-02,  8.00000000e-02,  9.00000000e-02,
        1.00000000e-01,  1.10000000e-01,  1.20000000e-01,  1.30000000e-01,
        1.40000000e-01,  1.50000000e-01,  1.60000000e-01,  1.70000000e-01,
        1.80000000e-01,  1.90000000e-01,  2.00000000e-01,  2.10000000e-01,
        2.20000000e-01,  2.30000000e-01,  2.40000000e-01,  2.50000000e-01,
        2.60000000e-01,  2.70000000e-01,  2.80000000e-01,  2.90000000e-01,
        3.00000000e-01,  3.10000000e-01,  3.20000000e-01,  3.30000000e-01,
        3.40000000e-01,  3.50000000e-01,  3.60000000e-01,  3.70000000e-01,
        3.80000000e-01,  3.90000000e-01,  4.00000000e-01,  4.10000000e-01,
        4.20076780e-01,  

In [50]:
file = "D:\\documents\\usp\\masters\\research\\dns_code\\GATT_DNS\\baseflow_gap_Re950_M01_h10_LR18\\mesh.mat"
meshMAT = loadmat(file)

In [51]:
meshMAT['Y']

array([[-1.00000000e-01, -9.00000000e-02, -8.00000000e-02,
        -7.00000000e-02, -6.00000000e-02, -5.00000000e-02,
        -4.00000000e-02, -3.00000000e-02, -2.00000000e-02,
        -1.00000000e-02,  0.00000000e+00,  1.00000000e-02,
         2.00000000e-02,  3.00000000e-02,  4.00000000e-02,
         5.00000000e-02,  6.00000000e-02,  7.00000000e-02,
         8.00000000e-02,  9.00000000e-02,  1.00000000e-01,
         1.10000000e-01,  1.20000000e-01,  1.30000000e-01,
         1.40000000e-01,  1.50000000e-01,  1.60000000e-01,
         1.70000000e-01,  1.80000000e-01,  1.90000000e-01,
         2.00000000e-01,  2.10000000e-01,  2.20000000e-01,
         2.30000000e-01,  2.40000000e-01,  2.50000000e-01,
         2.60000000e-01,  2.70000000e-01,  2.80000000e-01,
         2.90000000e-01,  3.00000000e-01,  3.10000000e-01,
         3.20000000e-01,  3.30000000e-01,  3.40000000e-01,
         3.50000000e-01,  3.60000000e-01,  3.70000000e-01,
         3.80000000e-01,  3.90000000e-01,  4.00000000e-0

In [52]:
print(mesh['X'].shape)
print(meshMAT['X'].shape)
print(mesh['Y'].shape)
print(meshMAT['Y'].shape)
print(mesh['Z'].shape)
print(meshMAT['Z'].shape)

(796,)
(1, 796)
(160,)
(1, 160)
(1,)
(1, 1)


In [53]:
meshMAT['X'].dtype

dtype('<f8')

In [75]:
var = 'Y'
sum(sum(mesh[var] - meshMAT[var] > 1e-15))
mesh[var] - meshMAT[var]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [92]:
mesh['X'][700:730]

array([494.14203302, 495.39203302, 496.64203302, 497.89203302,
       499.14203302, 500.39203302, 501.64203302, 502.89203302,
       504.14203302, 505.39203302, 506.64203302, 507.89203302,
       509.14203302, 510.39203302, 511.64203302, 512.89203302,
       514.14203302, 515.39203302, 516.64203302, 517.89203302,
       519.14203302, 520.39252104, 521.64309498, 522.89376996,
       524.14456376, 525.39549729, 526.64659516, 527.89788628,
       529.14940468, 530.40119035])

In [93]:
meshMAT['X'].reshape(-1)[700:730]


array([494.14203302, 495.39203302, 496.64203302, 497.89203302,
       499.14203302, 500.39203302, 501.64203302, 502.89203302,
       504.14203302, 505.39203302, 506.64203302, 507.89203302,
       509.14203302, 510.39203302, 511.64203302, 512.89203302,
       514.14203302, 515.39203302, 516.64203302, 517.89203302,
       519.14203302, 520.39252104, 521.64309498, 522.89376996,
       524.14456376, 525.39549729, 526.64659516, 527.89788628,
       529.14940468, 530.40119035])

In [1]:
import numpy as np

# Verificar se float128 está disponível
if hasattr(np, "float128"):
    print("float128 está disponível!")
else:
    print("float128 não está disponível neste sistema.")

float128 não está disponível neste sistema.


In [20]:
test = np.loadtxt('D:\\test.csv', dtype=np.float64)

In [22]:
test.astype(str)

array('1.0123456789012346', dtype='<U32')

In [18]:
mesh['Z']

array([1.])

In [19]:
meshMAT['Z']

array([[1]], dtype=uint8)

In [38]:
filemat =  "D:\\documents\\usp\\masters\\research\\dns_code\\GATT_DNS\\baseflow_gap_Re950_M01_h10_LR18\\flow_0000000000.mat"
filepy =  "D:\\documents\\usp\\masters\\research\\dns_code\\GATT_DNS\\py\\baseflow_gap_Re950_M01_h10_LR18\\flow_0000000000.h5"
#filemat =  "D:\\documents\\usp\\masters\\research\\dns_code\\GATT_DNS\\Red600-Ma05-L10-D5\\flow_0000000000.mat"
#filepy =  "D:\\documents\\usp\\masters\\research\\dns_code\\GATT_DNS\\py\\Re600-Ma05-L10-D5\\flow_0000000000.h5"

In [39]:
with h5py.File(filemat, "r") as fmat:
    print(fmat.keys())
    print(fmat['U'][()])
    Umat = fmat['U'][()]
    Rmat = fmat['R'][()]
    Vmat = fmat['V'][()]
    Wmat = fmat['W'][()]
    Emat = fmat['E'][()]

<KeysViewHDF5 ['E', 'R', 'U', 'V', 'W', 't']>
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [ 1.  1.  1. ...  1.  1.  1.]
 [ 1.  1.  1. ...  1.  1.  1.]
 [ 1.  1.  1. ...  1.  1.  1.]]


In [40]:
with h5py.File(filepy, "r") as fpy:
    print(fpy.keys())
    print(fpy['U'][()])
    Upy = fpy['U'][()]
    Rpy = fpy['R'][()]
    Vpy = fpy['V'][()]
    Wpy = fpy['W'][()]
    Epy = fpy['E'][()]

<KeysViewHDF5 ['E', 'R', 'U', 'V', 'W', 't']>
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [ 1.  1.  1. ...  1.  1.  1.]
 [ 1.  1.  1. ...  1.  1.  1.]
 [ 1.  1.  1. ...  1.  1.  1.]]


In [41]:
# Vmat==Vpy
print(Rpy[70,:50])
print(Rmat[70,:50])


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


In [43]:
print('Dimensões das variáveis:')
print(f'Rpy:{Rpy.shape} | Rmat:{Rmat.shape}')
print(f'Rpy:{Upy.shape} | Rmat:{Umat.shape}')
print(f'Rpy:{Vpy.shape} | Rmat:{Vmat.shape}')
print(f'Rpy:{Wpy.shape} | Rmat:{Wmat.shape}')
print(f'Rpy:{Epy.shape} | Rmat:{Emat.shape}')
print('Número de posições diferentes:')
print(f'Em R: {sum(sum(Rpy != Rmat))}')
print(f'Em U: {sum(sum(Upy != Umat))}')
print(f'Em V: {sum(sum(Vpy != Vmat))}')
print(f'Em W: {sum(sum(Wpy != Wmat))}')
print(f'Em E: {sum(sum(Epy != Emat))}')
print('Número de posições iguais:')
print(f'Em R: {sum(sum(Rpy == Rmat))}')
print(f'Em U: {sum(sum(Upy == Umat))}')
print(f'Em V: {sum(sum(Vpy == Vmat))}')
print(f'Em W: {sum(sum(Wpy == Wmat))}')
print(f'Em E: {sum(sum(Epy == Emat))}')



Dimensões das variáveis:
Rpy:(160, 796) | Rmat:(160, 796)
Rpy:(160, 796) | Rmat:(160, 796)
Rpy:(160, 796) | Rmat:(160, 796)
Rpy:(160, 796) | Rmat:(160, 796)
Rpy:(160, 796) | Rmat:(160, 796)
Número de posições diferentes:
Em R: 6222
Em U: 83602
Em V: 6222
Em W: 6222
Em E: 6222
Número de posições iguais:
Em R: 121138
Em U: 43758
Em V: 121138
Em W: 121138
Em E: 121138


In [45]:
print(sum(sum(Rpy - Rmat > 1e-12)))
print(sum(sum(Upy - Umat > 1e-12)))
print(sum(sum(Vpy - Vmat > 1e-12)))
print(sum(sum(Wpy - Wmat > 1e-12)))
print(sum(sum(Epy - Emat > 1e-12)))

0
13626
0
0
0


In [46]:
from scipy.io import savemat
savemat("z.mat", {"z":mesh['Z']})